### ISSUE TITLE
Generate:components leads to stylelint error

### ISSUE THREAD

**Issue by annsch** [db-ui/mono#1339] opened 2023-07-26 10:39 UTC
### Which generators are impacted?

- [X] All
- [ ] HTML
- [ ] React
- [ ] Angular
- [ ] Vue
- [ ] Web components
- [ ] Power Apps

### Reproduction case

- When generating new components by npm run generate:component we create an *.scss file with an empty block. This leads to stylelint errors when committing only this created files
- imports are separated by new lines which leads to linter error "There should be no empty line between import groups"

### Expected Behaviour

- create empty scss files without empty blocks _or_ e.g. // TODO comment
- prevent empty lines in imports

### Browser version

None

**Comment by mfranzke** [comment] 2023-07-26 10:47
@annsch is this a duplicate of https://github.com/db-ui/mono/issues/1338 ?

**Closed** 2023-07-26 10:58 UTC
Labels: bug
